# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robofont Knowledge Share
email: ahoy@ampershann.com
description: > # this means to ignore newlines until "baseurl:"
  This site is a first stab at collecting information, providing tips, tricks, and general knowhow for nascent type designers to learn the application Robofont.
  It is not officially endorsed by Robofont in any way. 
baseurl: "/robo-know" # the subpath of your site, e.g. /blog
url: "shannpersand.github.io/robo-know" # the base hostname & protocol for your site
twitter_username: ampershann
github_username:  shannpersand

# Collections
collections: 
  - glossary
  - shortcuts
  - tutorials
    output: true
  - drawing

# Build settings
markdown: kramdown
